In [4]:
#pip install tensorflow
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [5]:
df= pd.read_excel("Folds5x2_pp.xlsx")

In [7]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [8]:
sc=StandardScaler()
X=sc.fit_transform(X)
X

array([[-0.62951938, -0.98729659,  1.8204884 , -0.00951935],
       [ 0.74190911,  0.68104512,  1.1418628 , -0.97462052],
       [-1.95129733, -1.17301765, -0.18507756,  1.2898397 ],
       ...,
       [ 1.56583973,  1.57581141, -0.05709854, -2.52261812],
       [ 0.64797565,  1.19177803,  0.1011913 , -0.74790051],
       [ 0.26150656,  0.64641916,  0.66867722, -0.37254534]])

In [13]:
x_train,x_test,y_train,y_test=train_test_split(X,y)

In [23]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
#regression yaptığmızıdan activasyon eklemiyoruz
ann.add(tf.keras.layers.Dense(units=1))

In [25]:
ann.compile(optimizer='adam',metrics=['accuracy'],loss='mean_squared_error')
ann.fit(x_train,y_train,epochs=100,batch_size=32)

Epoch 1/100
225/225 [==============================] - 0s 757us/step - loss: 206856.8125 - accuracy: 0.0000e+00
Epoch 2/100
225/225 [==============================] - 0s 801us/step - loss: 206188.8125 - accuracy: 0.0000e+00
Epoch 3/100
225/225 [==============================] - 0s 743us/step - loss: 196129.2344 - accuracy: 0.0000e+00
Epoch 4/100
225/225 [==============================] - 0s 752us/step - loss: 156387.7031 - accuracy: 0.0000e+00
Epoch 5/100
225/225 [==============================] - 0s 757us/step - loss: 98032.4453 - accuracy: 0.0000e+00
Epoch 6/100
225/225 [==============================] - 0s 730us/step - loss: 50241.1875 - accuracy: 0.0000e+00
Epoch 7/100
225/225 [==============================] - 0s 768us/step - loss: 27641.6445 - accuracy: 0.0000e+00
Epoch 8/100
225/225 [==============================] - 0s 725us/step - loss: 20411.3809 - accuracy: 0.0000e+00
Epoch 9/100
225/225 [==============================] - 0s 761us/step - loss: 17048.3730 - accuracy: 0.0000e+

Epoch 76/100
225/225 [==============================] - 0s 770us/step - loss: 20.6181 - accuracy: 0.0000e+00
Epoch 77/100
225/225 [==============================] - 0s 757us/step - loss: 20.5708 - accuracy: 0.0000e+00
Epoch 78/100
225/225 [==============================] - 0s 712us/step - loss: 20.5406 - accuracy: 0.0000e+00
Epoch 79/100
225/225 [==============================] - 0s 761us/step - loss: 20.5347 - accuracy: 0.0000e+00
Epoch 80/100
225/225 [==============================] - 0s 732us/step - loss: 20.5824 - accuracy: 0.0000e+00
Epoch 81/100
225/225 [==============================] - 0s 723us/step - loss: 20.5909 - accuracy: 0.0000e+00
Epoch 82/100
225/225 [==============================] - 0s 699us/step - loss: 20.4269 - accuracy: 0.0000e+00
Epoch 83/100
225/225 [==============================] - 0s 674us/step - loss: 20.5353 - accuracy: 0.0000e+00
Epoch 84/100
225/225 [==============================] - 0s 725us/step - loss: 20.5425 - accuracy: 0.0000e+00
Epoch 85/100
225/22

In [35]:
from sklearn.metrics import confusion_matrix
np.set_printoptions(precision=2)
y_pred=ann.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))


[[460.11 466.68]
 [485.5  487.07]
 [444.42 442.43]
 ...
 [436.92 435.04]
 [472.64 472.82]
 [441.76 443.93]]
